name: Take screenshots

on:
  workflow_dispatch:

defaults:
  run:
    shell: "bash"

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1

jobs:
  take-screenshots:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # 6.0.2
        with:
          repository: AbdulrhmanGoni/denokv-gui-client
          ref: main

      - name: Install pnpm
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
        with:
          version: "11.15.1"

      - name: Setup a Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: "24.15.0"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build the app
        run: |
          pnpm run build
          pnpm run compile:ci

      - name: Take screenshots
        run: xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- pnpm run screenshots
      
      - name: Upload screenshots
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: screenshots
          path: screenshots/SettingsPage_*.png
